### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by c-smile** [8ctopus/sciter-components#1]
> A multi-line JSX expression must be wrapped in parentheses
> ```JS
> const component = (
>     <p> a paragraph </p>
> );
> ```

The *must* there is not correct.

This:

```JS
const component = <p>
     a paragraph 
</p>;
```
will work just fine. 

JSX expression should start in the same line as `=` or `return` statement.

Reason of this lies in famous "Automatic semicolon insertion": https://stackoverflow.com/questions/2846283/what-are-the-rules-for-javascripts-automatic-semicolon-insertion-asi

**Comment by c-smile** [comment]
Also about this

> A JSX expression must have exactly one outermost element or use an array

Fragments are also supported, so this:
```JS
// array alternative that works
const component = [
    <p> first paragraph </p>,
    <p> second paragraph </p>
];
```
can be written as 
```JS
// fragment
const component = <>
    <p> first paragraph </p>
    <p> second paragraph </p>
</>;
```

**Comment by 8ctopus** [comment]
Thank you for your feedback @c-smile , I will fix the issue today.

**Comment by 8ctopus** [comment]
DONE ba1b4afb16c56520199f01f4cb0e4faf55185f35
